Traceback (most recent call last):
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\wandb\sdk\wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'd_inner_hid'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\mich0003\Repos\BachelorPP\proactive\strategies\architecture\hawkes_training_wandb.py", line 33, in train
    d_inner=config.d_inner_hid,
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\wandb\sdk\wandb_config.py", line 166, in __getattr__
    ) from ke
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'd_inner_hid'
{'activation': 'default', 'batch_size': 4, 'd_inner': 256, 'd_k': 4, 'd_model': 64, 'd_rnn': 128, 'd_v': 4, 'data': 'data/Breakfast/', 'device': 'cuda', 'dropout': 0.1, 'epoch': 100, 'learning_rate': 0.0001, 'n_layer': 4, 'smooth': [0, 0.1]}
Loading All Datasets...
45 9