Training hawkes transformer...
{'batch_size': 4, 'd_k': 128, 'd_model': 256, 'd_rnn': 0, 'data': 'data/Breakfast/', 'device': 'cuda', 'dropout': 0.1, 'epochs': 35, 'learning_rate': 0.0001, 'n_head': 4, 'n_layers': 4, 'num_mix_components': 8, 'smooth': 0}
Loading All Datasets...
45 9
Traceback (most recent call last):
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\wandb\sdk\wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'mix'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\mich0003\Repos\BachelorPP\proactive\strategies\architecture\wandb\gmm_training_wandb.py", line 43, in train
    num_mix_components= config.mix
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\wandb\sdk\wandb_config.py", line 166, in __getattr__
    ) from ke
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'mix'