Training hawkes transformer...
{'activation': 'softplus', 'batch_size': 4, 'd_k': 128, 'd_model': 256, 'd_rnn': 0, 'data': 'data/Breakfast/', 'device': 'cuda', 'dropout': 0.1, 'epochs': 35, 'learning_rate': 0.0001, 'n_head': 4, 'n_layers': 4, 'smooth': 0}
Loading All Datasets...
45 9
[ Epoch 1 ]


  - (Training)   :  73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                         | 88/121 [00:05<00:01, 20.85it/s]


  - (Training)   :   0%|                                                                                                                                                                                                                          | 0/121 [00:00<?, ?it/s]
  - (Testing)     loglikelihood:  0.43369, accuracy:  0.57529, RMSE:  1.08971, elapse: 0.060 min
  - [Info] Maximum ll:  0.43369, Maximum accuracy:  0.57529, Minimum RMSE:  1.08971
improvement in epoch 1


  - (Training)   :  69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                 | 83/121 [00:05<00:01, 19.51it/s]


  - (Training)   :   0%|                                                                                                                                                                                                                          | 0/121 [00:00<?, ?it/s]
  - (Testing)     loglikelihood:  0.54870, accuracy:  0.59588, RMSE:  1.07262, elapse: 0.059 min
  - [Info] Maximum ll:  0.54870, Maximum accuracy:  0.59588, Minimum RMSE:  1.07262
improvement in epoch 2

Traceback (most recent call last):
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\mich0003\Repos\BachelorPP\proactive\strategies\architecture\wandb\hawkes_training_wandb.py", line 61, in train
    train_event, train_type, train_time = train_epoch(model, trainloader, optimizer, pred_loss_func, pred_loss_goal, config, epoch)
  File "C:\Users\mich0003\Repos\BachelorPP\proactive\strategies\architecture\wandb\hawkes_training_wandb.py", line 107, in train_epoch
    desc='  - (Training)   ', leave=False):
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\mich0003\AppData\Local\anaconda3\envs\proactive\lib\site-packages\torch\utils\data\dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 19768, 18744) exited unexpectedly